### ISSUE TITLE
Square brackets not handled

### ISSUE THREAD

**Issue by gazsiazasz** [vermut/intellij-ansible#112]
If I have this in my yaml, the IDE underlines it with red, however this is a correct syntax:
```
all:
  hosts:
  children:
    cafelatte:
      hosts:
        lofasz[005:008]:
```
