### ISSUE TITLE
Roles are not navigable when listed

### ISSUE THREAD

**Issue by mfriedenhagen** [vermut/intellij-ansible#3]
We have a lot of playbook where roles are given like this:

```yaml
  - roles:
    - first
    - second
```

Currently I may not navigate to these, when I write:
```yaml
  - roles:
    - role: first
    - role: second
```
they are found.
