### ISSUE TITLE
False positive error hightlight for lxc_container.container_command content

### ISSUE THREAD

**Issue by zeldigas** [vermut/intellij-ansible#36]
Example: 
```
    - name: Create container
      lxc_container:
        name: "{{ lxc_name }}"
        container_command: |
          mkdir -p /mnt/settings
```
