### ISSUE TITLE
Inline content is not properly parsed

### ISSUE THREAD

**Issue by mfriedenhagen** [vermut/intellij-ansible#4]
I sometime use inline templates:

```yaml
- name: Write JolokiaCollector.conf file
  copy:
    dest: /etc/diamond/collectors/JolokiaCollector.conf
    content: |
      host = 'localhost'
      enabled = True
      port = {{mamido_basepkg_metrics_diamond_jolokia_port}}
      {% if mamido_basepkg_metrics_diamond_jolokia_mbeans|length > 0 %}
      mbeans = '{{ mamido_basepkg_metrics_diamond_jolokia_mbeans|join("|") }}'
      {% endif %}\n
  notify: Restart diamond
  when: mamido_basepkg_metrics_diamond_jolokia_port
```

However the plugin is showing errors for this content.
