### ISSUE TITLE
YAML File Uncommenting a comment block from other editors will render an invalid YAML file with syntax errors

### ISSUE THREAD

**Issue by ye** [vermut/intellij-ansible#49]
Filed on IntelliJ YouTrack as https://youtrack.jetbrains.com/issue/PY-19430

But I think this might be the right place to report this issue. Description copied below.

When IntelliJ parses a block of comments inside a YAML file, it will render it invalid when the comments were NOT commented by IntelliJ. For instances:

This is a normal valid yaml file.

``` yaml
 build-www0:
  stage: build-containers
  script:
    - docker pull nginx:latest
    - ls -al www/static/css
    - ls -al www/static/js
    - ls -al www/static/js/vendor
    - ls -al www/static
  dependencies:
    - build-www-assets
build-www1:
  stage: build-containers
  script:
    - docker pull nginx:latest
    - ls -al www/static/css
    - ls -al www/static/js
    - ls -al www/static/js/vendor
    - ls -al www/static
  dependencies:
    - build-www-assets
```

Then edit it via another editor to comment this block. it becomes like this:

``` yaml
build-www0:
  stage: build-containers
  script:
    - docker pull nginx:latest
    - ls -al www/static/css
    - ls -al www/static/js
    - ls -al www/static/js/vendor
    - ls -al www/static
  dependencies:
    - build-www-assets
# build-www1:
#   stage: build-containers
#   script:
#     - docker pull nginx:latest
#     - ls -al www/static/css
#     - ls -al www/static/js
#     - ls -al www/static/js/vendor
#     - ls -al www/static
#   dependencies:
#     - build-www-assets
```

Then open the same YAML file in IntelliJ, use cmd+/ (I am on a Mac) to uncomment this block, it renders it invalid (syntax error).

``` yaml
build-www0:
  stage: build-containers
  script:
    - docker pull nginx:latest
    - ls -al www/static/css
    - ls -al www/static/js
    - ls -al www/static/js/vendor
    - ls -al www/static
  dependencies:
    - build-www-assets
 build-www1:
   stage: build-containers
   script:
     - docker pull nginx:latest
     - ls -al www/static/css
     - ls -al www/static/js
     - ls -al www/static/js/vendor
     - ls -al www/static
   dependencies:
     - build-www-assets 
```

This is happening in that in other editors (Sublime / TextWrangler), YAML file comments are prefixed with a "# " (an extra space) where as IntelliJ only prefixes with "#", and as a result, the direct reversal in IntelliJ's uncommenting will render a file with indentation off by one whitespace, the end result is a YAML file with syntax errors.

When uncommenting a block IntelliJ should replace the leading '#' with a white space instead of just chopping off the leading character (which is a '#').
